# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.burn_token_request import BurnTokenRequest  # noqa: E501
from neblioapi.rest import ApiException


class TestBurnTokenRequest(unittest.TestCase):
    """BurnTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBurnTokenRequest(self):
        """Test BurnTokenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.burn_token_request.BurnTokenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
