# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.get_faucet_response import GetFaucetResponse  # noqa: E501
from neblioapi.rest import ApiException


class TestGetFaucetResponse(unittest.TestCase):
    """GetFaucetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFaucetResponse(self):
        """Test GetFaucetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.get_faucet_response.GetFaucetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
