# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.send_token_response import SendTokenResponse  # noqa: E501
from neblioapi.rest import ApiException


class TestSendTokenResponse(unittest.TestCase):
    """SendTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendTokenResponse(self):
        """Test SendTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.send_token_response.SendTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
