# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_token_id_response import GetTokenIdResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTokenIdResponse(unittest.TestCase):
    """GetTokenIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTokenIdResponse(self):
        """Test GetTokenIdResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_token_id_response.GetTokenIdResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
