# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblio-api
from neblio-api.models.get_tx_response_vin import GetTxResponseVin  # noqa: E501
from neblio-api.rest import ApiException


class TestGetTxResponseVin(unittest.TestCase):
    """GetTxResponseVin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTxResponseVin(self):
        """Test GetTxResponseVin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblio-api.models.get_tx_response_vin.GetTxResponseVin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
