# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_transaction_info_response_vout import GetTransactionInfoResponseVout  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTransactionInfoResponseVout(unittest.TestCase):
    """GetTransactionInfoResponseVout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransactionInfoResponseVout(self):
        """Test GetTransactionInfoResponseVout"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_transaction_info_response_vout.GetTransactionInfoResponseVout()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
