# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.get_address_info_response_utxos import GetAddressInfoResponseUtxos  # noqa: E501
from neblioapi.rest import ApiException


class TestGetAddressInfoResponseUtxos(unittest.TestCase):
    """GetAddressInfoResponseUtxos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAddressInfoResponseUtxos(self):
        """Test GetAddressInfoResponseUtxos"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.get_address_info_response_utxos.GetAddressInfoResponseUtxos()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
