# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.get_token_metadata_response_metadata_of_issuence_data import GetTokenMetadataResponseMetadataOfIssuenceData  # noqa: E501
from neblioapi.rest import ApiException


class TestGetTokenMetadataResponseMetadataOfIssuenceData(unittest.TestCase):
    """GetTokenMetadataResponseMetadataOfIssuenceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTokenMetadataResponseMetadataOfIssuenceData(self):
        """Test GetTokenMetadataResponseMetadataOfIssuenceData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.get_token_metadata_response_metadata_of_issuence_data.GetTokenMetadataResponseMetadataOfIssuenceData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
