# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_token_metadata_response_metadata_of_issuance import GetTokenMetadataResponseMetadataOfIssuance  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTokenMetadataResponseMetadataOfIssuance(unittest.TestCase):
    """GetTokenMetadataResponseMetadataOfIssuance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTokenMetadataResponseMetadataOfIssuance(self):
        """Test GetTokenMetadataResponseMetadataOfIssuance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_token_metadata_response_metadata_of_issuance.GetTokenMetadataResponseMetadataOfIssuance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
