# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.error import Error  # noqa: E501
from neblioapi.rest import ApiException


class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError(self):
        """Test Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.error.Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
