# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.get_token_id_response import GetTokenIdResponse  # noqa: E501
from neblioapi.rest import ApiException


class TestGetTokenIdResponse(unittest.TestCase):
    """GetTokenIdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTokenIdResponse(self):
        """Test GetTokenIdResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.get_token_id_response.GetTokenIdResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
