# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.api.insight_api import InsightApi  # noqa: E501
from neblioapi.rest import ApiException


class TestInsightApi(unittest.TestCase):
    """InsightApi unit test stubs"""

    def setUp(self):
        self.api = neblioapi.api.insight_api.InsightApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_address(self):
        """Test case for get_address

        Returns address object  # noqa: E501
        """
        pass

    def test_get_address_balance(self):
        """Test case for get_address_balance

        Returns address balance in sats  # noqa: E501
        """
        pass

    def test_get_address_total_received(self):
        """Test case for get_address_total_received

        Returns total received by address in sats  # noqa: E501
        """
        pass

    def test_get_address_total_sent(self):
        """Test case for get_address_total_sent

        Returns total sent by address in sats  # noqa: E501
        """
        pass

    def test_get_address_unconfirmed_balance(self):
        """Test case for get_address_unconfirmed_balance

        Returns address unconfirmed balance in sats  # noqa: E501
        """
        pass

    def test_get_address_utxos(self):
        """Test case for get_address_utxos

        Returns all UTXOs at a given address  # noqa: E501
        """
        pass

    def test_get_block(self):
        """Test case for get_block

        Returns information regarding a Neblio block  # noqa: E501
        """
        pass

    def test_get_block_index(self):
        """Test case for get_block_index

        Returns block hash of block  # noqa: E501
        """
        pass

    def test_get_raw_tx(self):
        """Test case for get_raw_tx

        Returns raw transaction hex  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Utility API for calling several blockchain node functions  # noqa: E501
        """
        pass

    def test_get_sync(self):
        """Test case for get_sync

        Get node sync status  # noqa: E501
        """
        pass

    def test_get_tx(self):
        """Test case for get_tx

        Returns transaction object  # noqa: E501
        """
        pass

    def test_get_txs(self):
        """Test case for get_txs

        Get transactions by block or address  # noqa: E501
        """
        pass

    def test_send_tx(self):
        """Test case for send_tx

        Broadcasts a signed raw transaction to the network (not NTP1 specific)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
