# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_tx_response import GetTxResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTxResponse(unittest.TestCase):
    """GetTxResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTxResponse(self):
        """Test GetTxResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_tx_response.GetTxResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
