# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.get_token_metadata_response_metadata_of_utxo_user_data import GetTokenMetadataResponseMetadataOfUtxoUserData  # noqa: E501
from neblioapi.rest import ApiException


class TestGetTokenMetadataResponseMetadataOfUtxoUserData(unittest.TestCase):
    """GetTokenMetadataResponseMetadataOfUtxoUserData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTokenMetadataResponseMetadataOfUtxoUserData(self):
        """Test GetTokenMetadataResponseMetadataOfUtxoUserData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.get_token_metadata_response_metadata_of_utxo_user_data.GetTokenMetadataResponseMetadataOfUtxoUserData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
