# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import neblioapi
from neblioapi.models.broadcast_tx_request import BroadcastTxRequest  # noqa: E501
from neblioapi.rest import ApiException


class TestBroadcastTxRequest(unittest.TestCase):
    """BroadcastTxRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBroadcastTxRequest(self):
        """Test BroadcastTxRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = neblioapi.models.broadcast_tx_request.BroadcastTxRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
