# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.testnet_faucet_api import TestnetFaucetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTestnetFaucetApi(unittest.TestCase):
    """TestnetFaucetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.testnet_faucet_api.TestnetFaucetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_testnet_get_faucet(self):
        """Test case for testnet_get_faucet

        Withdraws testnet NEBL to the specified address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
