# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RpcRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'jsonrpc': 'str',
        'id': 'str',
        'method': 'str',
        'params': 'list[str]'
    }

    attribute_map = {
        'jsonrpc': 'jsonrpc',
        'id': 'id',
        'method': 'method',
        'params': 'params'
    }

    def __init__(self, jsonrpc='1.0', id='neblio-apis', method=None, params=None):  # noqa: E501
        """RpcRequest - a model defined in OpenAPI"""  # noqa: E501

        self._jsonrpc = None
        self._id = None
        self._method = None
        self._params = None
        self.discriminator = None

        self.jsonrpc = jsonrpc
        self.id = id
        self.method = method
        self.params = params

    @property
    def jsonrpc(self):
        """Gets the jsonrpc of this RpcRequest.  # noqa: E501

        JSON-RPC version  # noqa: E501

        :return: The jsonrpc of this RpcRequest.  # noqa: E501
        :rtype: str
        """
        return self._jsonrpc

    @jsonrpc.setter
    def jsonrpc(self, jsonrpc):
        """Sets the jsonrpc of this RpcRequest.

        JSON-RPC version  # noqa: E501

        :param jsonrpc: The jsonrpc of this RpcRequest.  # noqa: E501
        :type: str
        """
        if jsonrpc is None:
            raise ValueError("Invalid value for `jsonrpc`, must not be `None`")  # noqa: E501

        self._jsonrpc = jsonrpc

    @property
    def id(self):
        """Gets the id of this RpcRequest.  # noqa: E501

        Identifier of RCP caller  # noqa: E501

        :return: The id of this RpcRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RpcRequest.

        Identifier of RCP caller  # noqa: E501

        :param id: The id of this RpcRequest.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def method(self):
        """Gets the method of this RpcRequest.  # noqa: E501

        Name of the Neblio RPC method to call  # noqa: E501

        :return: The method of this RpcRequest.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this RpcRequest.

        Name of the Neblio RPC method to call  # noqa: E501

        :param method: The method of this RpcRequest.  # noqa: E501
        :type: str
        """
        if method is None:
            raise ValueError("Invalid value for `method`, must not be `None`")  # noqa: E501

        self._method = method

    @property
    def params(self):
        """Gets the params of this RpcRequest.  # noqa: E501

        Array of string params that should be passed to the RPC method.  # noqa: E501

        :return: The params of this RpcRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this RpcRequest.

        Array of string params that should be passed to the RPC method.  # noqa: E501

        :param params: The params of this RpcRequest.  # noqa: E501
        :type: list[str]
        """
        if params is None:
            raise ValueError("Invalid value for `params`, must not be `None`")  # noqa: E501

        self._params = params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RpcRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
