# coding: utf-8

"""
    Neblio REST API Suite

    APIs for Interacting with NTP1 Tokens & The Neblio Blockchain  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TestnetInsightApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def testnet_get_address(self, address, **kwargs):  # noqa: E501
        """Returns address object  # noqa: E501

        Returns NEBL address object containing information on a specific address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns address object  # noqa: E501

        Returns NEBL address object containing information on a specific address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_address_balance(self, address, **kwargs):  # noqa: E501
        """Returns address balance in sats  # noqa: E501

        Returns NEBL address balance in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_balance(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressBalanceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_balance_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_balance_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_balance_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns address balance in sats  # noqa: E501

        Returns NEBL address balance in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_balance_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressBalanceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address_balance" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address_balance`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}/balance', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressBalanceResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_address_total_received(self, address, **kwargs):  # noqa: E501
        """Returns total received by address in sats  # noqa: E501

        Returns total NEBL received by address in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_total_received(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressTotalReceivedResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_total_received_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_total_received_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_total_received_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns total received by address in sats  # noqa: E501

        Returns total NEBL received by address in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_total_received_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressTotalReceivedResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address_total_received" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address_total_received`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}/totalReceived', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressTotalReceivedResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_address_total_sent(self, address, **kwargs):  # noqa: E501
        """Returns total sent by address in sats  # noqa: E501

        Returns total NEBL sent by address in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_total_sent(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressTotalSentResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_total_sent_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_total_sent_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_total_sent_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns total sent by address in sats  # noqa: E501

        Returns total NEBL sent by address in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_total_sent_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressTotalSentResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address_total_sent" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address_total_sent`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}/totalSent', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressTotalSentResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_address_unconfirmed_balance(self, address, **kwargs):  # noqa: E501
        """Returns address unconfirmed balance in sats  # noqa: E501

        Returns NEBL address unconfirmed balance in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_unconfirmed_balance(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressUnconfirmedBalanceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_unconfirmed_balance_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_unconfirmed_balance_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_unconfirmed_balance_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns address unconfirmed balance in sats  # noqa: E501

        Returns NEBL address unconfirmed balance in satoshis  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_unconfirmed_balance_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressUnconfirmedBalanceResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address_unconfirmed_balance" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address_unconfirmed_balance`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}/unconfirmedBalance', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressUnconfirmedBalanceResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_address_utxos(self, address, **kwargs):  # noqa: E501
        """Returns all UTXOs at a given address  # noqa: E501

        Returns information on each Unspent Transaction Output contained at an address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_utxos(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressUtxosResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_address_utxos_with_http_info(address, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_address_utxos_with_http_info(address, **kwargs)  # noqa: E501
            return data

    def testnet_get_address_utxos_with_http_info(self, address, **kwargs):  # noqa: E501
        """Returns all UTXOs at a given address  # noqa: E501

        Returns information on each Unspent Transaction Output contained at an address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_address_utxos_with_http_info(address, async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address (required)
        :return: GetAddressUtxosResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_address_utxos" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'address' is set
        if ('address' not in params or
                params['address'] is None):
            raise ValueError("Missing the required parameter `address` when calling `testnet_get_address_utxos`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'address' in params:
            path_params['address'] = params['address']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/addr/{address}/utxo', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetAddressUtxosResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_block(self, blockhash, **kwargs):  # noqa: E501
        """Returns information regarding a Neblio block  # noqa: E501

        Returns blockchain data for a given block based upon the block hash  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_block(blockhash, async=True)
        >>> result = thread.get()

        :param async bool
        :param str blockhash: Block Hash (required)
        :return: GetBlockResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_block_with_http_info(blockhash, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_block_with_http_info(blockhash, **kwargs)  # noqa: E501
            return data

    def testnet_get_block_with_http_info(self, blockhash, **kwargs):  # noqa: E501
        """Returns information regarding a Neblio block  # noqa: E501

        Returns blockchain data for a given block based upon the block hash  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_block_with_http_info(blockhash, async=True)
        >>> result = thread.get()

        :param async bool
        :param str blockhash: Block Hash (required)
        :return: GetBlockResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['blockhash']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_block" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'blockhash' is set
        if ('blockhash' not in params or
                params['blockhash'] is None):
            raise ValueError("Missing the required parameter `blockhash` when calling `testnet_get_block`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'blockhash' in params:
            path_params['blockhash'] = params['blockhash']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/block/{blockhash}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetBlockResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_block_index(self, blockindex, **kwargs):  # noqa: E501
        """Returns block hash of block  # noqa: E501

        Returns the block hash of a block at a given block index  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_block_index(blockindex, async=True)
        >>> result = thread.get()

        :param async bool
        :param float blockindex: Block Index (required)
        :return: GetBlockIndexResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_block_index_with_http_info(blockindex, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_block_index_with_http_info(blockindex, **kwargs)  # noqa: E501
            return data

    def testnet_get_block_index_with_http_info(self, blockindex, **kwargs):  # noqa: E501
        """Returns block hash of block  # noqa: E501

        Returns the block hash of a block at a given block index  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_block_index_with_http_info(blockindex, async=True)
        >>> result = thread.get()

        :param async bool
        :param float blockindex: Block Index (required)
        :return: GetBlockIndexResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['blockindex']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_block_index" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'blockindex' is set
        if ('blockindex' not in params or
                params['blockindex'] is None):
            raise ValueError("Missing the required parameter `blockindex` when calling `testnet_get_block_index`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'blockindex' in params:
            path_params['blockindex'] = params['blockindex']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/block-index/{blockindex}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetBlockIndexResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_raw_tx(self, txid, **kwargs):  # noqa: E501
        """Returns raw transaction hex  # noqa: E501

        Returns raw transaction hex representing a NEBL transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_raw_tx(txid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str txid: Transaction ID (required)
        :return: GetRawTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_raw_tx_with_http_info(txid, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_raw_tx_with_http_info(txid, **kwargs)  # noqa: E501
            return data

    def testnet_get_raw_tx_with_http_info(self, txid, **kwargs):  # noqa: E501
        """Returns raw transaction hex  # noqa: E501

        Returns raw transaction hex representing a NEBL transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_raw_tx_with_http_info(txid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str txid: Transaction ID (required)
        :return: GetRawTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['txid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_raw_tx" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'txid' is set
        if ('txid' not in params or
                params['txid'] is None):
            raise ValueError("Missing the required parameter `txid` when calling `testnet_get_raw_tx`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'txid' in params:
            path_params['txid'] = params['txid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/rawtx/{txid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetRawTxResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_status(self, **kwargs):  # noqa: E501
        """Utility API for calling several blockchain node functions  # noqa: E501

        tility API for calling several blockchain node functions - getInfo, getDifficulty, getBestBlockHash, getLastBlockHash  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_status(async=True)
        >>> result = thread.get()

        :param async bool
        :param str q: Function to call, getInfo, getDifficulty, getBestBlockHash, or getLastBlockHash
        :return: GetStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_status_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_status_with_http_info(**kwargs)  # noqa: E501
            return data

    def testnet_get_status_with_http_info(self, **kwargs):  # noqa: E501
        """Utility API for calling several blockchain node functions  # noqa: E501

        tility API for calling several blockchain node functions - getInfo, getDifficulty, getBestBlockHash, getLastBlockHash  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_status_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str q: Function to call, getInfo, getDifficulty, getBestBlockHash, or getLastBlockHash
        :return: GetStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['q']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_status" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'q' in params:
            query_params.append(('q', params['q']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/status', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetStatusResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_sync(self, **kwargs):  # noqa: E501
        """Get node sync status  # noqa: E501

        Returns information on the node's sync progress  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_sync(async=True)
        >>> result = thread.get()

        :param async bool
        :return: GetSyncResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_sync_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_sync_with_http_info(**kwargs)  # noqa: E501
            return data

    def testnet_get_sync_with_http_info(self, **kwargs):  # noqa: E501
        """Get node sync status  # noqa: E501

        Returns information on the node's sync progress  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_sync_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: GetSyncResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_sync" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/sync', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetSyncResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_tx(self, txid, **kwargs):  # noqa: E501
        """Returns transaction object  # noqa: E501

        Returns NEBL transaction object representing a NEBL transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_tx(txid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str txid: Transaction ID (required)
        :return: GetTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_tx_with_http_info(txid, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_tx_with_http_info(txid, **kwargs)  # noqa: E501
            return data

    def testnet_get_tx_with_http_info(self, txid, **kwargs):  # noqa: E501
        """Returns transaction object  # noqa: E501

        Returns NEBL transaction object representing a NEBL transaction  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_tx_with_http_info(txid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str txid: Transaction ID (required)
        :return: GetTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['txid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_tx" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'txid' is set
        if ('txid' not in params or
                params['txid'] is None):
            raise ValueError("Missing the required parameter `txid` when calling `testnet_get_tx`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'txid' in params:
            path_params['txid'] = params['txid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/tx/{txid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetTxResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_get_txs(self, **kwargs):  # noqa: E501
        """Get transactions by block or address  # noqa: E501

        Returns all transactions by block or address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_txs(async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address
        :param str block: Block Hash
        :param float page: Page number to display
        :return: GetTxsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_get_txs_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.testnet_get_txs_with_http_info(**kwargs)  # noqa: E501
            return data

    def testnet_get_txs_with_http_info(self, **kwargs):  # noqa: E501
        """Get transactions by block or address  # noqa: E501

        Returns all transactions by block or address  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_get_txs_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str address: Address
        :param str block: Block Hash
        :param float page: Page number to display
        :return: GetTxsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['address', 'block', 'page']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_get_txs" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'address' in params:
            query_params.append(('address', params['address']))  # noqa: E501
        if 'block' in params:
            query_params.append(('block', params['block']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/txs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GetTxsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def testnet_send_tx(self, body, **kwargs):  # noqa: E501
        """Broadcasts a signed raw transaction to the network (not NTP1 specific)  # noqa: E501

        Broadcasts a signed raw transaction to the network. If successful returns the txid of the broadcast trasnaction.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_send_tx(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param SendTxRequest body: Object representing a transaction to broadcast (required)
        :return: BroadcastTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.testnet_send_tx_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.testnet_send_tx_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def testnet_send_tx_with_http_info(self, body, **kwargs):  # noqa: E501
        """Broadcasts a signed raw transaction to the network (not NTP1 specific)  # noqa: E501

        Broadcasts a signed raw transaction to the network. If successful returns the txid of the broadcast trasnaction.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.testnet_send_tx_with_http_info(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param SendTxRequest body: Object representing a transaction to broadcast (required)
        :return: BroadcastTxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method testnet_send_tx" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `testnet_send_tx`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/testnet/ins/tx/send', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BroadcastTxResponse',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
